require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enabled
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Rakefile'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false
